version: "3"

services:
  caddy:
    image: caddy
    ports:
      - "8080:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - "./mnt/github/:/mnt/github/"

        #renovate:
        #image: renovate
