version: "3"

services:
  caddy:
    image: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - "./mnt/github/:/mnt/github/"
      - "./cert/generated/:/etc/ssl/certs/self-signed/"

        #renovate:
        #image: renovat
