version: "3"

services:
  reproducible:
    build:
      context: .
      dockerfile: Dockerfile
    extra_hosts:
      - "localhost.localdomain:127.0.0.1"
    env_file: .env
    volumes:
      - "./output/:/mnt/"
